[build]
  command = "npm run build"       
  publish = "dist"                  
  base = "/"                         

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/style.css"                  
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
